kind = "api"
previewPath = "/api/"
title = "Sistema Bancário — API"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api/"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/banking-system", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "artifacts/banking-system/dist/server.js"]

[services.production.run.env]
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/healthz"
